name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: './build/*'  # Указываем только папку build
          target: '/var/www/myapp/build'  # Путь на сервере

      - name: Restart application with PM2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /var/www/myapp/build
            cp ../.env .env  # Копируем .env в папку build
            nvm use          # Убедитесь, что nvm настроен на сервере
            npm ci --omit=dev
            pm2 restart bin/server.js